package com.syncstudy.service;

import com.syncstudy.dto.response.ScheduleShortfallResponse;
import com.syncstudy.model.Availability;
import com.syncstudy.model.StudySession;
import com.syncstudy.model.Subject;
import com.syncstudy.repository.AvailabilityRepository;
import com.syncstudy.repository.StudySessionRepository;
import com.syncstudy.repository.SubjectRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.temporal.WeekFields;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Moteur de génération Greedy — CDC §4.2.2
 *
 * Règles appliquées :
 *  1. Priorisation hiérarchique  : Haute > Moyenne > Basse
 *  2. Non-chevauchement strict   : aucune session ne peut se superposer
 *  3. Respect min/max session    : fractionnement automatique si objectif > maxSessionMin
 *  4. Répartition équilibrée     : max 1 session par matière par jour par passe
 *  5. Rapport de sous-objectif   : heures non planifiées retournées à l'appelant
 */
@Service
public class PlanningAlgorithmService {

    private static final Map<String, Integer> PRIORITY_RANK = Map.of(
            "Haute",   3,
            "Moyenne", 2,
            "Basse",   1
    );

    private final SubjectRepository subjectRepository;
    private final AvailabilityRepository availabilityRepository;
    private final StudySessionRepository sessionRepository;

    public PlanningAlgorithmService(
            SubjectRepository subjectRepository,
            AvailabilityRepository availabilityRepository,
            StudySessionRepository sessionRepository
    ) {
        this.subjectRepository = subjectRepository;
        this.availabilityRepository = availabilityRepository;
        this.sessionRepository = sessionRepository;
    }

    // ── Résultat de génération ────────────────────────────────────────────────

    public record GenerationResult(
            List<StudySession> sessions,
            List<ScheduleShortfallResponse> shortfalls
    ) {}

    // ── Point d'entrée public ─────────────────────────────────────────────────

    /**
     * Génère un planning brouillon pour la semaine courante.
     *
     * @param userId         identifiant de l'utilisateur
     * @param restDayIndices jours de repos à ignorer (0=Dim … 6=Sam, convention JS)
     */
    public GenerationResult generateSchedule(String userId, List<Integer> restDayIndices) {

        List<Subject> subjects = subjectRepository.findByUserId(userId);
        List<Availability> availabilities = availabilityRepository.findByUserId(userId);
        List<StudySession> allSessions = sessionRepository.findByUserId(userId);

        LocalDate weekStart = currentWeekMonday();
        LocalDate weekEnd = weekStart.plusDays(7);

        // Calculer les heures déjà complétées par matière cette semaine
        // (seulement les sessions avec status "completed")
        java.util.Map<String, Double> completedHours = new java.util.HashMap<>();
        allSessions.stream()
                .filter(s -> "completed".equalsIgnoreCase(s.getStatus()))
                .filter(s -> s.getEndTime() != null)
                .filter(s -> s.getStartTime() != null
                        && !s.getStartTime().toLocalDate().isBefore(weekStart)
                        && s.getStartTime().toLocalDate().isBefore(weekEnd))
                .forEach(s -> {
                    double h = java.time.Duration.between(s.getStartTime(), s.getEndTime()).toMinutes() / 60.0;
                    completedHours.merge(s.getSubjectId(), h, Double::sum);
                });

        // C12 : supprimer les anciennes sessions auto-générées non complétées
        // et conserver les sessions manuelles + complétées.
        List<StudySession> autoGeneratedToDelete = allSessions.stream()
                .filter(StudySession::isAutoGenerated)
                .filter(s -> !"completed".equalsIgnoreCase(s.getStatus()))
                .toList();
        if (!autoGeneratedToDelete.isEmpty()) {
            sessionRepository.deleteAll(autoGeneratedToDelete);
        }

        // Les sessions non-brouillon existantes sont des contraintes dures (no-overlap)
        // Règle: seules les sessions futures bloquent la régénération.
        // Les sessions passées (y compris "completed") sont déjà comptées dans completedHours
        // et ne doivent pas empêcher le placement des créneaux restants.
        List<StudySession> existing = allSessions.stream()
                .filter(s -> !(s.isAutoGenerated() && !"completed".equalsIgnoreCase(s.getStatus())))
                .filter(s -> !s.isDraft())
                .filter(s -> {
                    if (s.getEndTime() == null) return false;
                    return s.getEndTime().isAfter(LocalDateTime.now(java.time.ZoneId.systemDefault()));
                })
                .toList();

        // Pas de matières ou pas de disponibilités → shortfall total
        if (subjects.isEmpty() || availabilities.isEmpty()) {
            return new GenerationResult(
                    List.of(),
                    buildShortfalls(
                            subjects,
                            remainingGoalsBySubject(subjects, completedHours),
                            completedHours,
                            availabilities,
                            restDayIndices
                    )
            );
        }

        // 1. Séparer cours et projets, puis trier chaque groupe par priorité décroissante
        List<Subject> courses = subjects.stream()
                .filter(s -> !"project".equalsIgnoreCase(s.getStudyType()))
                .sorted(Comparator.comparingInt(s -> -PRIORITY_RANK.getOrDefault(s.getPriority(), 1)))
                .toList();

        List<Subject> projects = subjects.stream()
                .filter(s -> "project".equalsIgnoreCase(s.getStudyType()))
                .sorted(Comparator.comparingInt(s -> -PRIORITY_RANK.getOrDefault(s.getPriority(), 1)))
                .toList();

        // Ordre de traitement : cours en premier, puis projets
        List<Subject> sorted = new ArrayList<>();
        sorted.addAll(courses);
        sorted.addAll(projects);

        // 2. Construction des fenêtres de disponibilité pour la semaine courante
        List<DayWindow> dayWindows = buildDayWindows(availabilities, weekStart, restDayIndices);

        // 3. Placement Greedy
        List<StudySession>  generated       = new ArrayList<>();
        Map<String, Double> unscheduledHours = new HashMap<>();

        for (Subject subject : sorted) {
            double hoursLeft = subject.getWeeklyGoalHours();
            // Déduire les heures déjà complétées cette semaine
            double alreadyDone = completedHours.getOrDefault(subject.getId(), 0.0);
            hoursLeft = Math.max(0, hoursLeft - alreadyDone);
            if (hoursLeft <= 0) {
                // Important: marquer explicitement l'objectif comme couvert
                // pour éviter un faux shortfall via la valeur par défaut.
                unscheduledHours.put(subject.getId(), 0.0);
                continue;
            }

            int    minMin = Math.max(1, subject.getMinSessionMin());
            int    maxMin = Math.max(minMin, subject.getMaxSessionMin());
            double minH   = minMin / 60.0;
            double maxH   = maxMin / 60.0;

            // Passes multiples pour répartir équitablement sur la semaine (règle 4)
            boolean progress = true;
            while (hoursLeft > minH / 2.0 && progress) {
                progress = false;

                for (DayWindow day : dayWindows) {
                    if (hoursLeft <= minH / 2.0) break;

                    // Règle 4 : au plus 1 session par matière par jour par passe
                    boolean placedToday = false;

                    for (SlotCursor slot : day.slots()) {
                        if (placedToday) break;
                        if (hoursLeft <= minH / 2.0) break;

                        // Avancer le curseur si chevauchement avec une session existante
                        advancePastOverlaps(slot, existing, generated);

                        // Vérifier que le curseur est encore dans les bornes du créneau
                        if (!slot.cursor.isBefore(slot.end)) continue;

                        double remainingInSlot = minutesBetween(slot.cursor, slot.end) / 60.0;
                        if (remainingInSlot < minH) continue;

                        double duration = Math.min(hoursLeft, Math.min(maxH, remainingInSlot));
                        if (duration < minH) continue;

                        LocalDateTime sessionStart = slot.cursor;
                        LocalDateTime sessionEnd   = sessionStart.plusMinutes(Math.round(duration * 60));

                        // Vérifier que la session ne dépasse pas la fin du créneau
                        if (sessionEnd.isAfter(slot.end)) {
                            sessionEnd = slot.end;
                            duration = minutesBetween(sessionStart, sessionEnd) / 60.0;
                            if (duration < minH) continue;
                        }

                        // Règle 2 : vérification finale du non-chevauchement
                        if (overlaps(sessionStart, sessionEnd, existing) ||
                                overlaps(sessionStart, sessionEnd, generated)) {
                            slot.cursor = slot.cursor.plusMinutes(30);
                            continue;
                        }

                        // Placement de la session — directement confirmée (pas de brouillon)
                        StudySession session = StudySession.builder()
                                .userId(userId)
                                .subjectId(subject.getId())
                                .title(subject.getName())
                                .startTime(sessionStart)
                                .endTime(sessionEnd)
                                .autoGenerated(true)
                                .draft(false)
                                .groupSession("group".equalsIgnoreCase(subject.getWorkMode()))
                                .status("planned")
                                .build();

                        generated.add(session);
                        hoursLeft -= duration;
                        // Avancer le curseur : fin de session + 30 min de pause
                        LocalDateTime nextCursor = sessionEnd.plusMinutes(30);
                        slot.cursor = nextCursor.isBefore(slot.end) ? nextCursor : slot.end;
                        placedToday = true;
                        progress    = true;
                    }
                }
            }

            unscheduledHours.put(subject.getId(), Math.max(0, hoursLeft));
        }

        // 4. Persistance des sessions générées
        List<StudySession> saved = sessionRepository.saveAll(generated);

        // 5. Rapport de sous-objectif enrichi
        List<ScheduleShortfallResponse> shortfalls = buildShortfalls(
                subjects,
                unscheduledHours,
                completedHours,
                availabilities,
                restDayIndices
        );

        return new GenerationResult(saved, shortfalls);
    }

    // ── Helpers privés ────────────────────────────────────────────────────────

    /** Génère avec fusion automatique des créneaux qui se chevauchent (après confirmation utilisateur). */
    public GenerationResult generateScheduleWithMerge(String userId, List<Integer> restDayIndices) {
        // Fusionner les disponibilités qui se chevauchent avant de générer
        List<Availability> availabilities = availabilityRepository.findByUserId(userId);
        List<Availability> merged = mergeOverlappingAvailabilities(availabilities);
        // Sauvegarder les disponibilités fusionnées
        availabilityRepository.deleteByUserId(userId);
        availabilityRepository.saveAll(merged);
        // Générer normalement
        return generateSchedule(userId, restDayIndices);
    }

    /** Fusionne les créneaux qui se chevauchent pour un même jour. */
    private List<Availability> mergeOverlappingAvailabilities(List<Availability> availabilities) {
        List<Availability> result = new ArrayList<>();
        // Grouper par jour
        java.util.Map<Integer, List<Availability>> byDay = availabilities.stream()
                .collect(Collectors.groupingBy(Availability::getDayOfWeek));
        for (java.util.Map.Entry<Integer, List<Availability>> entry : byDay.entrySet()) {
            List<Availability> daySlots = entry.getValue().stream()
                    .sorted(Comparator.comparing(Availability::getStartTime))
                    .collect(Collectors.toCollection(ArrayList::new));
            List<Availability> mergedDay = new ArrayList<>();
            for (Availability slot : daySlots) {
                if (mergedDay.isEmpty()) {
                    mergedDay.add(Availability.builder()
                            .userId(slot.getUserId())
                            .dayOfWeek(slot.getDayOfWeek())
                            .startTime(slot.getStartTime())
                            .endTime(slot.getEndTime())
                            .build());
                } else {
                    Availability last = mergedDay.get(mergedDay.size() - 1);
                    if (slot.getStartTime().compareTo(last.getEndTime()) <= 0) {
                        // Chevauchement → étendre
                        if (slot.getEndTime().compareTo(last.getEndTime()) > 0) {
                            last.setEndTime(slot.getEndTime());
                        }
                    } else {
                        mergedDay.add(Availability.builder()
                                .userId(slot.getUserId())
                                .dayOfWeek(slot.getDayOfWeek())
                                .startTime(slot.getStartTime())
                                .endTime(slot.getEndTime())
                                .build());
                    }
                }
            }
            result.addAll(mergedDay);
        }
        return result;
    }

    /** Lundi de la semaine ISO courante. */
    private LocalDate currentWeekMonday() {
        return LocalDate.now(java.time.ZoneId.systemDefault())
                .with(WeekFields.of(Locale.FRANCE).dayOfWeek(), 1);
    }

    /**
     * Construit une DayWindow par jour de disponibilité.
     * Si le jour est déjà passé cette semaine → utilise le même jour la semaine prochaine.
     * Convention dayOfWeek : 0=Dim, 1=Lun … 6=Sam (identique à JS / Availability model).
     */
    private List<DayWindow> buildDayWindows(
            List<Availability> availabilities,
            LocalDate weekStart,
            List<Integer> restDayIndices
    ) {
        LocalDate today = LocalDate.now(java.time.ZoneId.systemDefault());
        LocalDateTime now = LocalDateTime.now(java.time.ZoneId.systemDefault());
        List<DayWindow> windows = new ArrayList<>();

        for (int i = 0; i < 7; i++) {
            LocalDate dayThisWeek = weekStart.plusDays(i);
            // ISO : Lun=1 … Dim=7 → convertir en 0=Dim … 6=Sam
            int dow = dayThisWeek.getDayOfWeek().getValue() % 7;

            if (restDayIndices != null && restDayIndices.contains(dow)) continue;

            // Vérifier si ce jour a des disponibilités
            List<Availability> dayAvails = availabilities.stream()
                    .filter(a -> a.getDayOfWeek() == dow)
                    .toList();
            if (dayAvails.isEmpty()) continue;

            // Si le jour est passé (ou aujourd'hui mais tous les créneaux sont passés)
            // → utiliser le même jour la semaine prochaine
            LocalDate targetDay = dayThisWeek;
            if (dayThisWeek.isBefore(today)) {
                targetDay = dayThisWeek.plusWeeks(1);
            } else if (dayThisWeek.isEqual(today)) {
                // Vérifier si au moins un créneau est encore disponible aujourd'hui
                boolean hasRemainingSlot = dayAvails.stream().anyMatch(a -> {
                    LocalTime end = LocalTime.parse(a.getEndTime());
                    return today.atTime(end).isAfter(now);
                });
                if (!hasRemainingSlot) {
                    targetDay = dayThisWeek.plusWeeks(1);
                }
            }

            // Capturer dans une variable finale pour le lambda
            final LocalDate finalTargetDay = targetDay;
            final LocalDateTime finalNow = now;
            final boolean isToday = dayThisWeek.isEqual(today);

            List<SlotCursor> slots = dayAvails.stream()
                    .map(a -> {
                        LocalTime start = LocalTime.parse(a.getStartTime());
                        LocalTime end   = LocalTime.parse(a.getEndTime());
                        LocalDateTime slotStart = finalTargetDay.atTime(start);
                        LocalDateTime slotEnd   = finalTargetDay.atTime(end);
                        // Si c'est aujourd'hui et que le début est passé → avancer au moment actuel + 5 min
                        if (isToday && slotStart.isBefore(finalNow)) {
                            slotStart = finalNow.plusMinutes(5);
                        }
                        return new SlotCursor(slotStart, slotEnd);
                    })
                    .filter(s -> s.cursor.isBefore(s.end)) // ignorer les créneaux entièrement passés
                    .sorted(Comparator.comparing(s -> s.cursor))
                    .collect(Collectors.toCollection(ArrayList::new));

            // Détecter les chevauchements — lever une exception si trouvés
            for (int j = 0; j < slots.size() - 1; j++) {
                SlotCursor a = slots.get(j);
                SlotCursor b = slots.get(j + 1);
                if (a.end.isAfter(b.cursor)) { // a.end > b.cursor → chevauchement
                    throw new AvailabilityOverlapException(
                        "Chevauchement détecté le " + finalTargetDay.getDayOfWeek() +
                        " entre " + a.cursor.toLocalTime() + "-" + a.end.toLocalTime() +
                        " et " + b.cursor.toLocalTime() + "-" + b.end.toLocalTime()
                    );
                }
            }

            windows.add(new DayWindow(finalTargetDay, slots));
        }

        // Trier les fenêtres par date pour respecter l'ordre chronologique
        windows.sort(Comparator.comparing(DayWindow::date));
        return windows;
    }

    /** Avance le curseur du slot pour dépasser toute session qui chevauche sa position actuelle.
     *  Ne dépasse jamais la fin du créneau. */
    private void advancePastOverlaps(SlotCursor slot, List<StudySession> existing, List<StudySession> generated) {
        boolean moved = true;
        while (moved && slot.cursor.isBefore(slot.end)) {
            moved = false;
            for (StudySession s : existing) {
                if (s.getStartTime() == null || s.getEndTime() == null) continue;
                if (slot.cursor.isBefore(s.getEndTime()) && !slot.cursor.isBefore(s.getStartTime())) {
                    LocalDateTime newCursor = s.getEndTime().plusMinutes(30);
                    // Ne pas dépasser la fin du créneau
                    if (newCursor.isBefore(slot.end)) {
                        slot.cursor = newCursor;
                        moved = true;
                    } else {
                        slot.cursor = slot.end; // marquer le créneau comme épuisé
                        return;
                    }
                }
            }
            for (StudySession s : generated) {
                if (slot.cursor.isBefore(s.getEndTime()) && !slot.cursor.isBefore(s.getStartTime())) {
                    LocalDateTime newCursor = s.getEndTime().plusMinutes(30);
                    if (newCursor.isBefore(slot.end)) {
                        slot.cursor = newCursor;
                        moved = true;
                    } else {
                        slot.cursor = slot.end;
                        return;
                    }
                }
            }
        }
    }

    /** Vérifie si [start, end[ chevauche une session de la liste. */
    private boolean overlaps(LocalDateTime start, LocalDateTime end, List<StudySession> sessions) {
        for (StudySession s : sessions) {
            if (s.getStartTime() == null || s.getEndTime() == null) continue;
            if (start.isBefore(s.getEndTime()) && end.isAfter(s.getStartTime())) return true;
        }
        return false;
    }

    private double minutesBetween(LocalDateTime from, LocalDateTime to) {
        return java.time.Duration.between(from, to).toMinutes();
    }

    private List<ScheduleShortfallResponse> buildShortfalls(
            List<Subject> subjects,
            Map<String, Double> unscheduledHours,
            Map<String, Double> completedHours,
            List<Availability> availabilities,
            List<Integer> restDayIndices
    ) {
        // Calcul des heures disponibles totales cette semaine
        LocalDate weekStart = currentWeekMonday();
        final double[] totalAvailableHoursArr = {0.0};
        try {
            List<DayWindow> dayWindows = buildDayWindows(availabilities, weekStart, restDayIndices);
            totalAvailableHoursArr[0] = dayWindows.stream()
                    .flatMap(dw -> dw.slots().stream())
                    .mapToDouble(slot -> minutesBetween(slot.cursor, slot.end) / 60.0)
                    .sum();
        } catch (AvailabilityOverlapException ex) {
            // En cas de chevauchement, calculer les heures brutes sans validation
            totalAvailableHoursArr[0] = availabilities.stream()
                    .mapToDouble(a -> {
                        LocalTime startT = LocalTime.parse(a.getStartTime());
                        LocalTime endT   = LocalTime.parse(a.getEndTime());
                        return java.time.Duration.between(startT, endT).toMinutes() / 60.0;
                    }).sum();
        }
        final double totalAvailableHours = totalAvailableHoursArr[0];

        // Heures totales demandées par tous les sujets
        double totalNeeded = subjects.stream()
                .mapToDouble(Subject::getWeeklyGoalHours)
                .sum();

        return subjects.stream()
                .filter(s -> unscheduledHours.getOrDefault(s.getId(), s.getWeeklyGoalHours()) > 0.05)
                .map(s -> {
                    double missing = Math.round(
                            unscheduledHours.getOrDefault(s.getId(), s.getWeeklyGoalHours()) * 10.0) / 10.0;
                    // On suggère d'ajouter des disponibilités si les heures totales
                    // disponibles sont insuffisantes pour couvrir tous les objectifs
                    boolean needsMore = totalAvailableHours < totalNeeded;
                    return ScheduleShortfallResponse.builder()
                            .subjectId(s.getId())
                            .subjectName(s.getName())
                            .hoursMissing(missing)
                            .studyType(s.getStudyType() != null ? s.getStudyType() : "course")
                            .totalAvailableHours(Math.round(totalAvailableHours * 10.0) / 10.0)
                            .hoursNeeded(Math.max(0, s.getWeeklyGoalHours() - completedHours.getOrDefault(s.getId(), 0.0)))
                            .needsMoreAvailability(needsMore)
                            .build();
                })
                .toList();
    }

    private Map<String, Double> remainingGoalsBySubject(
            List<Subject> subjects,
            Map<String, Double> completedHours
    ) {
        Map<String, Double> remaining = new HashMap<>();
        for (Subject s : subjects) {
            double left = Math.max(0, s.getWeeklyGoalHours() - completedHours.getOrDefault(s.getId(), 0.0));
            if (left > 0.05) {
                remaining.put(s.getId(), left);
            }
        }
        return remaining;
    }

    // ── Types internes ────────────────────────────────────────────────────────

    /** Curseur mutable dans un créneau de disponibilité. */
    private static class SlotCursor {
        LocalDateTime cursor;
        final LocalDateTime end;
        SlotCursor(LocalDateTime cursor, LocalDateTime end) {
            this.cursor = cursor;
            this.end    = end;
        }
    }

    private record DayWindow(LocalDate date, List<SlotCursor> slots) {}
}
