import { Injectable, signal, computed } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Subject, Availability } from '../models/subject.model';
import { StudySession } from '../models/session.model';
import { SchedulerService } from './scheduler.service';
import { ToastService } from './toast.service';
import { API_PATHS } from '../api/api.constants';
import { Observable, catchError, map, of, tap } from 'rxjs';

export interface ScheduleShortfall {
  subjectId: string;
  subjectName: string;
  hoursMissing: number;
  studyType?: 'course' | 'project';
  totalAvailableHours?: number;
  hoursNeeded?: number;
  needsMoreAvailability?: boolean;
}

export interface CompletedPlanningInfo {
  subjectId: string;
  subjectName: string;
}

/**
 * Formate une Date en chaîne ISO locale SANS décalage UTC ("2026-05-02T18:00:00").
 *
 * Pourquoi ne pas utiliser .toISOString() ?
 * .toISOString() renvoie l'heure UTC ("2026-05-02T17:00:00.000Z" pour UTC+1).
 * Le backend utilise LocalDateTime (sans fuseau) : il stockerait 17:00 au lieu de 18:00.
 * Cette fonction envoie directement l'heure affichée à l'utilisateur.
 */
function toLocalISO(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}` +
         `T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

@Injectable({ providedIn: 'root' })
export class PlanningService {
  private _subjects = signal<Subject[]>([]);
  private _sessions = signal<StudySession[]>([]);
  private _availabilities = signal<Availability[]>([]);
  private _activeId = signal<string | null>(null);
  private _lastScheduleShortfall = signal<ScheduleShortfall[]>([]);
  private _lastOverlapInfo = signal<{ overlapDetail: string; message: string } | null>(null);
  private _lastCompletedPlanningInfo = signal<CompletedPlanningInfo[]>([]);

  readonly subjects = this._subjects.asReadonly();
  readonly sessions = this._sessions.asReadonly();
  readonly activeId = this._activeId.asReadonly();
  readonly availabilities = this._availabilities.asReadonly();
  readonly lastScheduleShortfall = this._lastScheduleShortfall.asReadonly();
  readonly lastOverlapInfo = this._lastOverlapInfo.asReadonly();
  readonly lastCompletedPlanningInfo = this._lastCompletedPlanningInfo.asReadonly();
  readonly activeSession = computed(() =>
    this._sessions().find((s) => s.id === this._activeId()) ?? null
  );

  readonly hasDraftAutoSessions = computed(() =>
    this._sessions().some((s) => s.isDraft && s.isAutoGenerated)
  );

  constructor(
    private scheduler: SchedulerService,
    private http: HttpClient,
    private toast: ToastService
  ) {}

  /** Chargement initial depuis le backend — à appeler au login ou au démarrage */
  loadFromBackend(): void {
    this.http.get<Subject[]>(API_PATHS.subjects).subscribe({
      next: (data) => this._subjects.set(data),
      error: () => {},
    });

    // 1. Propager les sessions de groupe du user courant vers les autres membres
    this.http.post<any>(API_PATHS.sessionMigrateGroupSessions, {}).subscribe({ error: () => {} });

    // 2. Recevoir les copies des sessions de groupe des autres membres (sessions futures uniquement)
    //    Après cette étape, chaque user possède SES PROPRES copies → la suppression est définitive
    this.http.post<any>(API_PATHS.sessionSyncGroupSessions, {}).subscribe({
      next: () => this.loadSessionsFromBackend(), // recharger après synchro pour voir les nouvelles copies
      error: () => this.loadSessionsFromBackend(),
    });

    this.http.get<Availability[]>(API_PATHS.availabilities).subscribe({
      next: (data) => this._availabilities.set(data),
      error: () => {},
    });
  }

  private loadSessionsFromBackend(): void {
    this.http.get<StudySession[]>(API_PATHS.sessions).subscribe({
      next: (data) => {
        const sessions = data.map((s: any) => ({
          ...s,
          // Java boolean "groupSession" → Jackson sérialise en "groupSession" (pas "isGroupSession")
          // On normalise ici pour que le frontend ait toujours isGroupSession correctement rempli
          isGroupSession: s.isGroupSession ?? s.groupSession ?? false,
          startTime: new Date(s.startTime),
          endTime: new Date(s.endTime),
          actualStart: s.actualStart ? new Date(s.actualStart) : undefined,
          actualEnd: s.actualEnd ? new Date(s.actualEnd) : undefined,
        }));

        // Déduplication : garder la session "completed" en cas de doublon
        const seen = new Map<string, any>();
        for (const s of sessions) {
          const key = `${s.subjectId}|${toLocalISO(new Date(s.startTime)).slice(0, 16)}`;
          const existing = seen.get(key);
          if (!existing) {
            seen.set(key, s);
          } else if (s.isCompleted && !existing.isCompleted) {
            seen.set(key, s);
          }
        }
        this._sessions.set(Array.from(seen.values()));
      },
      error: () => {},
    });
  }

  addSubjectHttp(s: Omit<Subject, 'id'>): void {
    this.http.post<Subject>(API_PATHS.subjects, s).subscribe({
      next: (created) => this._subjects.update((list) => [...list, created]),
      error: () => {
        // Ne pas ajouter localement : la matière n'est pas en base → éviter l'incohérence
        this.toast.show('Impossible de sauvegarder la matière. Vérifiez votre connexion.', 'error');
      },
    });
  }

  updateSubjectHttp(updated: Subject): void {
    this.http.put<Subject>(API_PATHS.subject(updated.id), updated).subscribe({
      next: (saved) =>
        this._subjects.update((list) =>
          list.map((s) => (s.id === saved.id ? saved : s))
        ),
      error: () => {
        this.toast.show('Impossible de mettre à jour la matière. Vérifiez votre connexion.', 'error');
      },
    });
  }

  deleteSubjectHttp(id: string): void {
    this.http.delete<void>(API_PATHS.subject(id)).subscribe({
      next: () => this.deleteSubject(id),
      error: () => {
        this.toast.show('Impossible de supprimer la matière. Vérifiez votre connexion.', 'error');
      },
    });
  }

  setAvailabilitiesHttp(availabilities: Availability[]): void {
    this.setAvailabilities(availabilities);
    this.http.post<Availability[]>(API_PATHS.availabilities, availabilities).subscribe({
      next: (saved) => this._availabilities.set(saved),
      error: () => {},
    });
  }

  startSessionHttp(id: string): void {
    const session = this._sessions().find(s => s.id === id);
    if (!session) return;

    this.startSession(id); // mise à jour locale immédiate

    // Toujours créer/vérifier la session en base avant de démarrer
    const payload = {
      subjectId:  session.subjectId,
      groupId:    session.groupId ?? null,
      title:      session.note ?? '',
      startTime:  toLocalISO(session.startTime instanceof Date ? session.startTime : new Date(session.startTime)),
      endTime:    toLocalISO(session.endTime instanceof Date ? session.endTime : new Date(session.endTime)),
      objectives: session.objectives ?? [],
    };

    // Essayer de démarrer directement avec l'ID actuel
    this.http.post<void>(API_PATHS.sessionStart(id), {}).subscribe({
      next: () => {}, // session existe en base avec cet ID
      error: () => {
        // Session pas en base → créer puis démarrer
        this.http.post<any>(API_PATHS.sessions, payload).subscribe({
          next: (created) => {
            const realId = created.id;
            this._sessions.update(list =>
              list.map(s => s.id === id ? { ...s, id: realId, isDraft: false, isAutoGenerated: false } : s)
            );
            this._activeId.set(realId); // IMPORTANT : mettre à jour l'ID actif
            this.http.post<void>(API_PATHS.sessionStart(realId), {}).subscribe();
          },
          error: () => {} // garder l'ID local en dernier recours
        });
      }
    });
  }

  stopSessionHttp(): void {
    const id = this._activeId();
    if (!id) return;
    const now = new Date();

    // Mise à jour locale immédiate
    this._sessions.update((list) =>
      list.map((s) => {
        if (s.id !== id) return s;
        const previousSeconds = s.pausedElapsedSeconds ?? 0;
        const startRef = s.actualStart ?? s.startTime;
        const secs = Math.max(0, Math.round((now.getTime() - new Date(startRef).getTime()) / 1000));
        const totalSeconds = previousSeconds + secs;
        const totalMinutes = totalSeconds > 0 ? Math.max(1, Math.ceil(totalSeconds / 60)) : 0;
        return {
          ...s,
          isCompleted: true,
          actualEnd: now,
          pausedElapsedSeconds: totalSeconds,
          actualDurationMinutes: totalMinutes,
        };
      })
    );
    this._activeId.set(null);

    // Persister en base
    this.http.post<void>(API_PATHS.sessionStop(id), {}).subscribe({
      next: () => this.reloadSessions(),
      error: () => {
        // Recharger quand même pour avoir l'état réel du backend
        this.reloadSessions();
      }
    });
  }

  pauseActiveSessionHttp(sessionId: string, elapsedSeconds: number): void {
    const safeSeconds = Math.max(0, Math.round(elapsedSeconds));
    const elapsedMinutes = safeSeconds > 0 ? Math.max(1, Math.ceil(safeSeconds / 60)) : 0;
    this._sessions.update((list) =>
      list.map((s) =>
        s.id === sessionId
          ? { ...s, pausedElapsedSeconds: safeSeconds, actualDurationMinutes: elapsedMinutes, actualStart: undefined }
          : s
      )
    );
    this._activeId.set(null);

    this.http.patch<void>(API_PATHS.session(sessionId), {
      pausedElapsedSeconds: safeSeconds,
      actualDurationMinutes: elapsedMinutes,
      actualStart: null,
      status: 'planned',
    }).subscribe({ error: () => {} });
  }

  pauseAndSaveSessionHttp(
    sessionId: string,
    elapsedSeconds: number,
    data: {
      note?: string;
      sessionGoal?: string;
      todos?: any[];
      flashcards?: any[];
      courseItems?: any[];
      attachments?: any[];
    }
  ): void {
    const safeSeconds = Math.max(0, Math.round(elapsedSeconds));
    const elapsedMinutes = safeSeconds > 0 ? Math.max(1, Math.ceil(safeSeconds / 60)) : 0;

    this._sessions.update((list) =>
      list.map((s) =>
        s.id === sessionId
          ? {
              ...s,
              ...data,
              pausedElapsedSeconds: safeSeconds,
              actualDurationMinutes: elapsedMinutes,
              actualStart: undefined,
            }
          : s
      )
    );
    this._activeId.set(null);

    this.http.patch<void>(API_PATHS.session(sessionId), {
      ...data,
      pausedElapsedSeconds: safeSeconds,
      actualDurationMinutes: elapsedMinutes,
      actualStart: null,
      status: 'planned',
    }).subscribe({ error: () => {} });
  }

  private reloadSessions(): void {
    this.http.get<StudySession[]>(API_PATHS.sessions).subscribe({
      next: (data) => {
        const currentDrafts = this._sessions().filter(s => s.isDraft && s.isAutoGenerated);
        const mapped = data.map((s: any) => ({
          ...s,
          // Normalisation isGroupSession (Jackson sérialise parfois en "groupSession")
          isGroupSession: s.isGroupSession ?? s.groupSession ?? false,
          startTime: new Date(s.startTime),
          endTime: new Date(s.endTime),
          actualStart: s.actualStart ? new Date(s.actualStart) : undefined,
          actualEnd: s.actualEnd ? new Date(s.actualEnd) : undefined,
        }));

        // Déduplication par subjectId+startTime (comme loadSessionsFromBackend)
        const seen = new Map<string, any>();
        for (const s of mapped) {
          const key = `${s.subjectId}|${toLocalISO(new Date(s.startTime)).slice(0, 16)}`;
          const existing = seen.get(key);
          if (!existing) {
            seen.set(key, s);
          } else if (s.isCompleted && !existing.isCompleted) {
            seen.set(key, s);
          }
        }
        const fromBackend = Array.from(seen.values());

        // Fusionner : sessions backend + brouillons locaux non encore en base
        const backendIds = new Set(fromBackend.map((s: any) => s.id));
        const localOnlyDrafts = currentDrafts.filter(d => !backendIds.has(d.id));
        this._sessions.set([...fromBackend, ...localOnlyDrafts]);
      },
      error: () => {}
    });
  }

  generateScheduleHttp(restDayIndices: number[] = [], mergeDuplicates = false): Observable<ScheduleShortfall[]> {
    // Vider les shortfalls précédents immédiatement
    this._lastScheduleShortfall.set([]);
    this._lastOverlapInfo.set(null);
    this._lastCompletedPlanningInfo.set([]);

    return this.http.post<any>(
      API_PATHS.sessionGenerate, { restDayIndices, mergeDuplicates }
    ).pipe(
      map((response) => {
        if (response.requiresMerge) {
          this._lastOverlapInfo.set({ overlapDetail: response.overlapDetail, message: response.message });
          return [] as ScheduleShortfall[];
        }
        this._lastOverlapInfo.set(null);

        // Conserver toutes les sessions manuelles + toutes les sessions terminées
        // (même si elles étaient autoGenerated) pour garder l'historique visible.
        const kept = this._sessions().filter((s) => !s.isAutoGenerated || !!s.isCompleted);

        // Indicateur explicite : matières déjà terminées cette semaine
        const completedInfos = Array.from(
          new Set(
            kept
              .filter((s) => !!s.isCompleted)
              .map((s) => s.subjectId)
          )
        ).map((subjectId) => ({
          subjectId,
          subjectName: this._subjects().find((x) => x.id === subjectId)?.name ?? subjectId,
        }));
        this._lastCompletedPlanningInfo.set(completedInfos);

        const newSessions = (response.sessions ?? []).map((s: any) => ({
          ...s,
          startTime: new Date(s.startTime),
          endTime: new Date(s.endTime),
          isDraft: false,
          isAutoGenerated: true,
        }));
        this._sessions.set([...kept, ...newSessions]);
        this._lastScheduleShortfall.set(response.shortfalls ?? []);
        return (response.shortfalls ?? []) as ScheduleShortfall[];
      }),
      catchError((err) => {
        if (err.status === 409 && err.error?.requiresMerge) {
          this._lastOverlapInfo.set({ overlapDetail: err.error.overlapDetail, message: err.error.message });
          return of([] as ScheduleShortfall[]);
        }
        const shortfall = this.generateSchedule(restDayIndices);
        return of(shortfall);
      })
    );
  }

  /** Utilisé à l'inscription d'un nouvel étudiant pour démarrer sans données mock. */
  resetForNewStudent(): void {
    this._subjects.set([]);
    this._sessions.set([]);
    this._availabilities.set([]);
    this._activeId.set(null);
    this._lastScheduleShortfall.set([]);
  }

  /** Vide les shortfalls affichés */
  clearShortfall(): void {
    this._lastScheduleShortfall.set([]);
  }

  setAvailabilities(availabilities: Availability[]): void {
    this._availabilities.set(availabilities);
  }

  addSubject(s: Omit<Subject, 'id'>): void {
    const minSessionMin = s.minSessionMin ?? 45;
    const maxSessionMin = s.maxSessionMin ?? 120;
    this._subjects.update((list) => [
      ...list,
      { ...s, id: Math.random().toString(36).substring(2, 9), minSessionMin, maxSessionMin },
    ]);
  }

  updateSubject(updated: Subject): void {
    this._subjects.update((list) =>
      list.map((s) => (s.id === updated.id ? updated : s))
    );
  }

  deleteSubject(id: string): void {
    this._subjects.update((list) => list.filter((s) => s.id !== id));
    this._sessions.update((list) => list.filter((s) => s.subjectId !== id));
  }

  /**
   * Fusionne un nouveau brouillon auto-généré : conserve sessions manuelles / validées.
   * Retourne les écarts d'objectif (heures non planifiées).
   */
  generateSchedule(restDayIndices: number[] = []): ScheduleShortfall[] {
    const kept = this._sessions().filter((s) => !(s.isDraft && s.isAutoGenerated));
    const result = this.scheduler.generateSchedule(
      this._subjects(),
      this._availabilities(),
      new Date(),
      kept,
      restDayIndices
    );
    const { sessions: raw, unscheduledHours } = result;
    const flagged = raw.map((s) => ({
      ...s,
      isDraft: true,
      isAutoGenerated: true,
    }));
    this._sessions.set([...kept, ...flagged]);

    const subjects = this._subjects();
    const shortfall: ScheduleShortfall[] = Object.entries(unscheduledHours)
      .filter(([, h]) => h > 0.05)
      .map(([id, h]) => {
        const subject = subjects.find((x) => x.id === id);
        return {
          subjectId: id,
          subjectName: subject?.name ?? id,
          hoursMissing: Math.round(h * 10) / 10,
          studyType: subject?.studyType as 'course' | 'project' | undefined,
          totalAvailableHours: Math.round((result.totalAvailableHours ?? 0) * 10) / 10,
          hoursNeeded: subject?.weeklyGoalHours,
          needsMoreAvailability: (result.totalAvailableHours ?? 0) < (result.totalNeededHours ?? 0),
        };
      });
    this._lastScheduleShortfall.set(shortfall);
    return shortfall;
  }

  /** Valide toutes les sessions auto-générées en brouillon (CDC §4.2.3).
   *  Sauvegarde en base uniquement les sessions avec ID local (pas encore en MongoDB). */
  confirmDraftSchedule(): void {
    const drafts = this._sessions().filter(s => s.isDraft && s.isAutoGenerated);

    // Marquer localement comme non-brouillon immédiatement
    this._sessions.update((list) =>
      list.map((s) =>
        s.isDraft && s.isAutoGenerated ? { ...s, isDraft: false } : s
      )
    );
    this._lastScheduleShortfall.set([]);

    // Sauvegarder en base UNIQUEMENT les sessions locales (pas celles du backend)
    const localDrafts = drafts.filter(s => !(s as any)._fromBackend);
    localDrafts.forEach(draft => {
      const localId = draft.id;
      const payload = {
        subjectId:  draft.subjectId,
        groupId:    draft.groupId ?? null,
        title:      draft.note ?? '',
        startTime:  toLocalISO(draft.startTime instanceof Date ? draft.startTime : new Date(draft.startTime)),
        endTime:    toLocalISO(draft.endTime instanceof Date ? draft.endTime : new Date(draft.endTime)),
        objectives: draft.objectives ?? [],
      };
      this.http.post<any>(API_PATHS.sessions, payload).subscribe({
        next: (created) => {
          // Remplacer l'ID local par le vrai ID MongoDB
          this._sessions.update(list =>
            list.map(s => s.id === localId ? { ...s, id: created.id } : s)
          );
        },
        error: () => {}
      });
    });
  }

  /** Supprime le brouillon auto-généré sans valider (local + backend). */
  cancelDraftSchedule(): void {
    this._sessions.update((list) =>
      list.filter((s) => !(s.isDraft && s.isAutoGenerated))
    );
    // Nettoyage backend en best-effort
    this.http.delete<void>(API_PATHS.sessionDrafts).subscribe();
  }

  addSession(session: Omit<StudySession, 'id'>): string {
    const id = Math.random().toString(36).substring(2, 9);
    this._sessions.update((list) => [...list, { ...session, id }]);
    return id;
  }

  /** Crée une session en base et utilise le vrai ID MongoDB retourné */
  addSessionHttp(session: Omit<StudySession, 'id'>): void {
    const startIso = toLocalISO(session.startTime instanceof Date ? session.startTime : new Date(session.startTime));
    const endIso   = toLocalISO(session.endTime instanceof Date ? session.endTime : new Date(session.endTime));

    // Vérifier si une session identique existe déjà localement (éviter les doublons)
    const alreadyExists = this._sessions().some(s =>
      s.subjectId === session.subjectId &&
      Math.abs(new Date(s.startTime).getTime() - new Date(session.startTime).getTime()) < 60_000
    );
    if (alreadyExists) return;

    const payload = {
      subjectId:   session.subjectId,
      groupId:     session.groupId ?? null,
      title:       '',
      startTime:   startIso,
      endTime:     endIso,
      objectives:  session.objectives ?? [],
    };
    this.http.post<any>(API_PATHS.sessions, payload).subscribe({
      next: (created) => {
        this._sessions.update((list) => [...list, {
          ...session,
          id: created.id,
          startTime: new Date(created.startTime ?? session.startTime),
          endTime:   new Date(created.endTime ?? session.endTime),
        }]);
      },
      error: () => {
        const id = Math.random().toString(36).substring(2, 9);
        this._sessions.update((list) => [...list, { ...session, id }]);
      }
    });
  }

  /** Met à jour le créneau et la matière d'une session existante via PATCH */
  updateSessionSlotHttp(sessionId: string, startTime: Date, endTime: Date, subjectId: string): void {
    const patch = {
      startTime: toLocalISO(startTime),
      endTime:   toLocalISO(endTime),
      subjectId,
    };
    this._sessions.update(list =>
      list.map(s => s.id === sessionId
        ? { ...s, startTime, endTime, subjectId }
        : s
      )
    );
    this.http.patch<void>(API_PATHS.session(sessionId), patch).subscribe({ error: () => {} });
  }

  /**
   * Vérifie si un créneau (start → end) est couvert par au moins une disponibilité.
   * Retourne true si couvert, false sinon.
   */
  checkAvailabilityForSlot(start: Date, end: Date): boolean {
    const avs = this._availabilities();
    if (!avs.length) return false;
    const day = start.getDay(); // 0=Dimanche … 6=Samedi
    const startHHmm = `${String(start.getHours()).padStart(2, '0')}:${String(start.getMinutes()).padStart(2, '0')}`;
    const endHHmm   = `${String(end.getHours()).padStart(2, '0')}:${String(end.getMinutes()).padStart(2, '0')}`;
    return avs.some(
      (av) => av.dayOfWeek === day && av.startTime <= startHHmm && av.endTime >= endHHmm
    );
  }

  /**
   * Crée une session de groupe en base via HTTP, puis appelle `onCreated` avec l'objet créé.
   * Utilisé par la création de session partagée pour enchaîner l'émission socket avec le vrai ID.
   */
  createGroupSessionHttp(
    session: Omit<StudySession, 'id'>,
    onCreated: (created: StudySession) => void,
    onError?: () => void
  ): void {
    const startIso = toLocalISO(session.startTime instanceof Date ? session.startTime : new Date(session.startTime));
    const endIso   = toLocalISO(session.endTime   instanceof Date ? session.endTime   : new Date(session.endTime));
    // Inclure le nom de la matière dans le titre pour l'affichage chez les membres
    const subjectName = this._subjects().find(s => s.id === session.subjectId)?.name ?? '';
    const payload  = {
      subjectId:      session.subjectId,
      groupId:        session.groupId ?? null,
      title:          subjectName,
      startTime:      startIso,
      endTime:        endIso,
      objectives:     session.objectives ?? [],
      isGroupSession: true,
    };
    this.http.post<any>(API_PATHS.sessions, payload).subscribe({
      next: (raw) => {
        const created: StudySession = {
          ...session,
          id:            raw.id,
          startTime:     new Date(raw.startTime ?? startIso),
          endTime:       new Date(raw.endTime   ?? endIso),
          isGroupSession: true,
        };
        this._sessions.update((list) => [...list, created]);
        onCreated(created);
      },
      error: () => onError?.(),
    });
  }

  /** Fusionne ou crée une session partagée reçue par Socket.io (CDC §4.3.2) */
  mergeSharedSessionFromSocket(partial: {
    id: string;
    subjectId?: string;
    groupId?: string;
    startTime: Date;
    endTime: Date;
  }): void {
    this._sessions.update((list) => {
      const i = list.findIndex((x) => x.id === partial.id);
      const existing = i >= 0 ? list[i]! : null;
      if (existing) {
        const c = [...list];
        c[i] = {
          ...existing,
          startTime: new Date(partial.startTime),
          endTime: new Date(partial.endTime),
          groupId: partial.groupId ?? existing.groupId,
          subjectId: partial.subjectId ?? existing.subjectId,
        };
        return c;
      }
      const sid = partial.subjectId;
      if (!sid) return list;
      return [
        ...list,
        {
          id: partial.id,
          subjectId: sid,
          startTime: new Date(partial.startTime),
          endTime: new Date(partial.endTime),
          isCompleted: false,
          isGroupSession: true,
          groupId: partial.groupId,
          objectives: [],
        },
      ];
    });
  }

  completeSession(id: string): void {
    this._sessions.update((list) =>
      list.map((s) => (s.id === id ? { ...s, isCompleted: true } : s))
    );
  }

  deleteSession(id: string): void {
    // Suppression optimiste locale immédiate : la session disparaît de l'UI sans attendre le backend.
    // On NE recharge PAS les sessions après suppression — cela évite que la session
    // réapparaisse si le backend renvoie encore des copies croisées de membres du groupe.
    this._sessions.update((list) => list.filter((s) => s.id !== id));
    this.http.delete<void>(API_PATHS.session(id)).subscribe({ error: () => {} });
  }

  /** Supprime uniquement la copie de l'utilisateur courant sans affecter les autres membres */
  deleteSessionCopyOnly(id: string): void {
    this._sessions.update((list) => list.filter((s) => s.id !== id));
    this.http.delete<void>(`${API_PATHS.session(id)}?forAll=false`).subscribe({ error: () => {} });
  }

  updateSessionTimes(id: string, start: Date, end: Date): void {
    this._sessions.update((list) =>
      list.map((s) => (s.id === id ? { ...s, startTime: start, endTime: end } : s))
    );
  }

  updateObjectives(sessionId: string, objectives: string[]): void {
    this._sessions.update((list) =>
      list.map((s) => (s.id === sessionId ? { ...s, objectives } : s))
    );
  }

  updateSessionNote(sessionId: string, note: string): void {
    this._sessions.update((list) =>
      list.map((s) => (s.id === sessionId ? { ...s, note } : s))
    );
    // Persister la note en base
    this.http.patch<void>(API_PATHS.session(sessionId), { note }).subscribe({ error: () => {} });
  }

  /** Sauvegarde les données enrichies puis stoppe la session en séquence */
  saveSessionDataAndStop(sessionId: string, data: {
    note?: string;
    sessionGoal?: string;
    todos?: any[];
    flashcards?: any[];
    courseItems?: any[];
    attachments?: any[];
  }): void {
    const now = new Date();

    // Mise à jour locale immédiate
    this._sessions.update((list) =>
      list.map((s) => {
        if (s.id !== sessionId) return s;
        const previousSeconds = s.pausedElapsedSeconds ?? 0;
        const startRef = s.actualStart ?? s.startTime;
        const secs = Math.max(0, Math.round((now.getTime() - new Date(startRef).getTime()) / 1000));
        const totalSeconds = previousSeconds + secs;
        const totalMinutes = totalSeconds > 0 ? Math.max(1, Math.ceil(totalSeconds / 60)) : 0;
        return {
          ...s,
          ...data,
          isCompleted: true,
          actualEnd: now,
          pausedElapsedSeconds: totalSeconds,
          actualDurationMinutes: totalMinutes,
        };
      })
    );
    this._activeId.set(null);

    // Sauvegarder données + stopper en une seule requête PATCH puis POST stop
    const current = this._sessions().find(s => s.id === sessionId);
    const previousSeconds = current?.pausedElapsedSeconds ?? 0;
    const startRef = current?.actualStart ?? now;
    const computedSecs = Math.max(0, Math.round((now.getTime() - new Date(startRef).getTime()) / 1000));
    const totalSeconds = previousSeconds + computedSecs;

    const patchPayload = {
      ...data,
      actualEnd: toLocalISO(now),
      pausedElapsedSeconds: totalSeconds,
      actualDurationMinutes: totalSeconds > 0 ? Math.max(1, Math.ceil(totalSeconds / 60)) : 0,
    };

    this.http.patch<void>(API_PATHS.session(sessionId), patchPayload).subscribe({
      next: () => {
        this.http.post<void>(API_PATHS.sessionStop(sessionId), {}).subscribe({
          next: () => this.reloadSessions(),
          error: () => this.reloadSessions()
        });
      },
      error: () => {
        // Si patch échoue, stopper quand même
        this.http.post<void>(API_PATHS.sessionStop(sessionId), {}).subscribe({
          next: () => this.reloadSessions(),
          error: () => this.reloadSessions()
        });
      }
    });
  }

  /** Sauvegarde toutes les données enrichies d'une session (notes, todos, flashcards, etc.) */
  saveSessionData(sessionId: string, data: {
    note?: string;
    sessionGoal?: string;
    todos?: any[];
    flashcards?: any[];
    courseItems?: any[];
    attachments?: any[];
  }): void {
    // Mise à jour locale
    this._sessions.update((list) =>
      list.map((s) => (s.id === sessionId ? { ...s, ...data } : s))
    );
    // Persistance en base
    this.http.patch<void>(API_PATHS.session(sessionId), data).subscribe({ error: () => {} });
  }

  /**
   * Partage une session personnelle avec un groupe.
   * Met à jour la session localement après confirmation du backend.
   */
  shareSessionWithGroup(sessionId: string, groupId: string): Observable<void> {
    const session = this._sessions().find(s => s.id === sessionId);
    const subjectName = session
      ? (this._subjects().find(s => s.id === session.subjectId)?.name ?? '')
      : '';
    return this.http.post<any>(API_PATHS.sessionShare(sessionId), { groupId, title: subjectName }).pipe(
      tap(() => {
        this._sessions.update(list =>
          list.map(s => s.id === sessionId
            ? { ...s, isGroupSession: true, groupId }
            : s
          )
        );
      }),
      map(() => void 0)
    );
  }

  startSession(id: string): void {
    const now = new Date();
    this._activeId.set(id);
    this._sessions.update((list) =>
      list.map((s) => (s.id === id ? { ...s, actualStart: now } : s))
    );
  }

  stopSession(): void {
    const id = this._activeId();
    if (id) {
      const now = new Date();
      this._sessions.update((list) =>
        list.map((s) => {
          if (s.id !== id) return s;
          const startRef = s.actualStart ?? s.startTime;
          const mins = (now.getTime() - new Date(startRef).getTime()) / 60_000;
          return {
            ...s,
            isCompleted: true,
            actualEnd: now,
            actualDurationMinutes: Math.max(0, Math.round(mins)),
          };
        })
      );
    }
    this._activeId.set(null);
  }
}
