package com.syncstudy.controller;

import com.syncstudy.dto.request.CreateSessionRequest;
import com.syncstudy.dto.request.GenerateScheduleRequest;
import com.syncstudy.model.StudySession;
import com.syncstudy.service.AvailabilityOverlapException;
import com.syncstudy.service.PlanningAlgorithmService;
import com.syncstudy.service.SessionService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/sessions")
@PreAuthorize("isAuthenticated()")
public class SessionController {

    private final SessionService sessionService;
    private final PlanningAlgorithmService planningAlgorithmService;

    public SessionController(
            SessionService sessionService,
            PlanningAlgorithmService planningAlgorithmService
    ) {
        this.sessionService = sessionService;
        this.planningAlgorithmService = planningAlgorithmService;
    }

    private Map<String, Object> toFrontend(StudySession s) {
        Map<String, Object> m = new HashMap<>();
        m.put("id",                    s.getId());
        m.put("subjectId",             s.getSubjectId());
        m.put("groupId",               s.getGroupId());
        m.put("title",                 s.getTitle() != null ? s.getTitle() : "");
        m.put("startTime",             s.getStartTime());
        m.put("endTime",               s.getEndTime());
        m.put("actualStart",           s.getActualStart());
        m.put("actualEnd",             s.getActualEnd());
        m.put("actualDurationMinutes", s.getActualDurationMinutes());
        m.put("pausedElapsedSeconds",  s.getPausedElapsedSeconds());
        m.put("status",                s.getStatus());   // "planned" | "unscheduled" | "in_progress" | "completed" | "expired"
        m.put("isCompleted",           "completed".equalsIgnoreCase(s.getStatus()));
        // Fallback : si la session a un groupId, c'est forcément une session de groupe
        // (nécessaire pour les sessions créées avant le correctif @JsonProperty)
        m.put("isGroupSession",        s.isGroupSession() || (s.getGroupId() != null && !s.getGroupId().isBlank()));
        m.put("isDraft",               s.isDraft());
        m.put("isAutoGenerated",       s.isAutoGenerated());
        m.put("objectives",            s.getObjectives());
        m.put("note",                  s.getNote());
        m.put("sessionGoal",           s.getSessionGoal());
        m.put("todos",                 s.getTodos());
        m.put("flashcards",            s.getFlashcards());
        m.put("courseItems",           s.getCourseItems());
        m.put("attachments",           s.getAttachments());
        return m;
    }

    /**
     * Génère un planning brouillon via l'algorithme Greedy (CDC §4.2.2).
     * Retourne { sessions: [...], shortfalls: [...] }
     * En cas de chevauchement de disponibilités : { overlaps: [...], requiresMerge: true }
     */
    @PostMapping("/generate")
    public ResponseEntity<Map<String, Object>> generate(
            Authentication authentication,
            @RequestBody(required = false) GenerateScheduleRequest req
    ) {
        List<Integer> restDays = (req != null && req.getRestDayIndices() != null)
                ? req.getRestDayIndices()
                : List.of();

        boolean mergeDuplicates = req != null && Boolean.TRUE.equals(req.getMergeDuplicates());

        try {
            PlanningAlgorithmService.GenerationResult result =
                    planningAlgorithmService.generateSchedule(authentication.getName(), restDays);

            Map<String, Object> response = new HashMap<>();
            response.put("sessions",   result.sessions().stream().map(this::toFrontend).toList());
            response.put("shortfalls", result.shortfalls());
            return ResponseEntity.ok(response);

        } catch (AvailabilityOverlapException e) {
            if (mergeDuplicates) {
                // L'utilisateur a confirmé la fusion → générer avec fusion
                PlanningAlgorithmService.GenerationResult result =
                        planningAlgorithmService.generateScheduleWithMerge(authentication.getName(), restDays);
                Map<String, Object> response = new HashMap<>();
                response.put("sessions",   result.sessions().stream().map(this::toFrontend).toList());
                response.put("shortfalls", result.shortfalls());
                response.put("mergedOverlaps", true);
                return ResponseEntity.ok(response);
            }
            // Chevauchement détecté — demander confirmation à l'utilisateur
            Map<String, Object> response = new HashMap<>();
            response.put("requiresMerge", true);
            response.put("overlapDetail", e.getOverlapDetail());
            response.put("message", "Des créneaux de disponibilité se chevauchent. Voulez-vous les fusionner automatiquement pour générer le planning ?");
            return ResponseEntity.status(org.springframework.http.HttpStatus.CONFLICT).body(response);
        }
    }

    @GetMapping
    public ResponseEntity<List<Map<String, Object>>> list(Authentication authentication) {
        String userId = authentication.getName();
        // Dédupliquer avant de retourner pour garantir des données propres
        sessionService.deduplicateSessions(userId);
        return ResponseEntity.ok(
                sessionService.getAllVisibleSessions(userId)
                        .stream().map(this::toFrontend).toList()
        );
    }

    @PostMapping
    public ResponseEntity<Map<String, Object>> create(
            Authentication authentication,
            @Valid @RequestBody CreateSessionRequest req
    ) {
        return ResponseEntity.ok(toFrontend(sessionService.createSession(authentication.getName(), req)));
    }

    @PutMapping("/{id}")
    public ResponseEntity<Map<String, Object>> update(
            Authentication authentication,
            @PathVariable String id,
            @Valid @RequestBody CreateSessionRequest req
    ) {
        return ResponseEntity.ok(toFrontend(sessionService.updateSession(authentication.getName(), id, req)));
    }

    @PatchMapping("/{id}")
    public ResponseEntity<Void> patch(
            Authentication authentication,
            @PathVariable String id,
            @RequestBody Map<String, Object> fields
    ) {
        sessionService.patchSession(authentication.getName(), id, fields);
        return ResponseEntity.ok().build();
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(
            Authentication authentication,
            @PathVariable String id,
            @RequestParam(defaultValue = "true") boolean forAll) {
        if (forAll) {
            // Suppression complète : retire la session ET les copies de tous les membres (propriétaire)
            sessionService.deleteSession(authentication.getName(), id);
        } else {
            // Suppression partielle : retire uniquement la copie du membre demandeur
            sessionService.deleteSessionCopyOnly(authentication.getName(), id);
        }
        return ResponseEntity.ok().build();
    }

    /** Supprime toutes les sessions brouillon auto-générées (nettoyage manuel) */
    @DeleteMapping("/drafts")
    public ResponseEntity<Void> deleteDrafts(Authentication authentication) {
        sessionService.deleteDraftSessions(authentication.getName());
        return ResponseEntity.ok().build();
    }

    /** Déduplique les sessions (supprime les doublons) */
    @PostMapping("/deduplicate")
    public ResponseEntity<Void> deduplicate(Authentication authentication) {
        sessionService.deduplicateSessions(authentication.getName());
        return ResponseEntity.ok().build();
    }

    /**
     * Propage les sessions de groupe existantes aux membres qui n'en ont pas encore une copie.
     * À appeler une fois pour migrer les données existantes.
     */
    @PostMapping("/migrate-group-sessions")
    public ResponseEntity<Map<String, Object>> migrateGroupSessions(Authentication authentication) {
        int created = sessionService.propagateExistingGroupSessions(authentication.getName());
        return ResponseEntity.ok(Map.of("created", created));
    }

    /**
     * Synchronise les sessions de groupe des autres membres vers l'utilisateur courant.
     * Crée des copies uniquement pour les sessions futures non-expirées que l'utilisateur ne possède pas.
     * Appelé au démarrage de l'application pour garantir la cohérence des données.
     */
    @PostMapping("/sync-group-sessions")
    public ResponseEntity<Map<String, Object>> syncGroupSessions(Authentication authentication) {
        int synced = sessionService.syncGroupSessionsForUser(authentication.getName());
        return ResponseEntity.ok(Map.of("synced", synced));
    }

    /**
     * Partage une session personnelle avec tous les membres d'un groupe.
     * Met à jour isGroupSession=true et crée des copies pour les autres membres.
     */
    @PostMapping("/{id}/share")
    public ResponseEntity<Map<String, Object>> share(
            Authentication authentication,
            @PathVariable String id,
            @RequestBody Map<String, String> body
    ) {
        String groupId = body.get("groupId");
        if (groupId == null || groupId.isBlank()) {
            return ResponseEntity.badRequest().build();
        }
        String title = body.get("title");
        return ResponseEntity.ok(toFrontend(
                sessionService.shareSessionWithGroup(authentication.getName(), id, groupId, title)
        ));
    }

    @PostMapping("/{id}/start")
    public ResponseEntity<Void> start(Authentication authentication, @PathVariable String id) {
        sessionService.startSession(authentication.getName(), id);
        return ResponseEntity.ok().build();
    }

    @PostMapping("/{id}/stop")
    public ResponseEntity<Void> stop(Authentication authentication, @PathVariable String id) {
        sessionService.stopSession(authentication.getName(), id);
        return ResponseEntity.ok().build();
    }
}
