package com.syncstudy.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Document(collection = "study_sessions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class StudySession {
    @Id
    private String id;

    @NotBlank
    private String userId;

    @NotBlank
    private String subjectId;

    private String groupId;
    private String title;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private LocalDateTime actualStart;
    private LocalDateTime actualEnd;
    private Integer actualDurationMinutes;

    @Builder.Default
    private String status = "planned"; // planned | in_progress | completed | skipped

    @Builder.Default
    private boolean autoGenerated = false;

    @Builder.Default
    private boolean draft = false;

    @JsonProperty("isGroupSession")
    @Builder.Default
    private boolean groupSession = false;

    @Builder.Default
    private List<String> objectives = new ArrayList<>();

    private String note;

    // Données de session enrichies
    @Builder.Default
    private List<java.util.Map<String, Object>> todos = new ArrayList<>();

    @Builder.Default
    private List<java.util.Map<String, Object>> flashcards = new ArrayList<>();

    @Builder.Default
    private List<java.util.Map<String, Object>> courseItems = new ArrayList<>();

    @Builder.Default
    private List<java.util.Map<String, Object>> attachments = new ArrayList<>();

    private String sessionGoal;

    private Integer pausedElapsedSeconds; // secondes écoulées avant la pause
}
