package com.syncstudy.repository;

import com.syncstudy.model.StudySession;
import org.springframework.data.mongodb.repository.MongoRepository;

import java.time.LocalDateTime;
import java.util.List;

public interface StudySessionRepository extends MongoRepository<StudySession, String> {
    List<StudySession> findByUserId(String userId);
    List<StudySession> findByUserIdAndStartTimeBetween(String userId, LocalDateTime from, LocalDateTime to);
    /** Toutes les sessions (tous utilisateurs) dont le début est dans la fenêtre donnée */
    List<StudySession> findByStartTimeBetween(LocalDateTime from, LocalDateTime to);
    List<StudySession> findByGroupId(String groupId);
    /** Toutes les sessions ayant un groupId dans la liste donnée */
    List<StudySession> findByGroupIdIn(List<String> groupIds);
    // Supprime toutes les sessions brouillon auto-générées d'un utilisateur
    void deleteByUserIdAndDraftTrueAndAutoGeneratedTrue(String userId);
}
