export interface StudySession {
  id: string;
  subjectId: string;
  title?: string;
  startTime: Date;
  endTime: Date;
  isCompleted: boolean;
  actualStart?: Date;
  actualEnd?: Date;
  actualDurationMinutes?: number;
  pausedElapsedSeconds?: number; // secondes écoulées avant la pause
  isGroupSession?: boolean;
  groupId?: string;
  objectives?: string[];
  note?: string;
  sessionGoal?: string;
  todos?: { id: string; text: string; done: boolean; authorName?: string }[];
  flashcards?: { id: string; question: string; answer: string }[];
  courseItems?: { id: string; type: string; title: string; content: string; authorName?: string }[];
  attachments?: {
    id: string;
    name: string;
    size: string;
    dataUrl?: string;
    mimeType?: string;
  }[];
  isDraft?: boolean;
  isAutoGenerated?: boolean;
  /** Statut côté backend : "planned" | "in_progress" | "completed" | "expired" | "unscheduled" */
  status?: string;
}
